apiVersion: v1
kind: Namespace
metadata:
  name: reactodoui-ns
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reactodoui-app-deployment
  namespace: reactodoui-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: reactodoui-app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: reactodoui-app
    spec:
      containers:
        - name: reactodoui-app
          image: aksclsuterregistry.azurecr.io/reacttodoui:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: reactodoui-ingress
  namespace: reactodoui-ns
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: reactodoui-app-service
              port:
                number: 80

---
apiVersion: v1
kind: Service
metadata:
  name: reactodoui-app-service
  namespace: reactodoui-ns
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: reactodoui-app
  ports:
    - port: 80
      targetPort: 80
